# Generated by Django 4.0.2 on 2022-02-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_billinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
