# Generated by Django 4.0.2 on 2022-02-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_medicalinfo_deviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='userID',
            field=models.CharField(max_length=60),
        ),
    ]
