# Generated by Django 4.0.2 on 2022-02-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_billinginfo_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='userID',
        ),
    ]
