# Generated by Django 4.0.2 on 2022-02-22 02:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_remove_medicalinfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Patient'), ('D', 'Provider')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
