# Generated by Django 4.0.2 on 2022-02-22 02:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Patient'), ('D', 'Provider')], max_length=3),
        ),
    ]
