# Generated by Django 4.0.2 on 2022-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False, verbose_name='userID'),
        ),
    ]
